require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PeaksController do

  # This should return the minimal set of attributes required to create a valid
  # Peak. As you add validations to Peak, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all peaks as @peaks" do
      peak = Peak.create! valid_attributes
      get :index
      assigns(:peaks).should eq([peak])
    end
  end

  describe "GET show" do
    it "assigns the requested peak as @peak" do
      peak = Peak.create! valid_attributes
      get :show, :id => peak.id.to_s
      assigns(:peak).should eq(peak)
    end
  end

  describe "GET new" do
    it "assigns a new peak as @peak" do
      get :new
      assigns(:peak).should be_a_new(Peak)
    end
  end

  describe "GET edit" do
    it "assigns the requested peak as @peak" do
      peak = Peak.create! valid_attributes
      get :edit, :id => peak.id.to_s
      assigns(:peak).should eq(peak)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Peak" do
        expect {
          post :create, :peak => valid_attributes
        }.to change(Peak, :count).by(1)
      end

      it "assigns a newly created peak as @peak" do
        post :create, :peak => valid_attributes
        assigns(:peak).should be_a(Peak)
        assigns(:peak).should be_persisted
      end

      it "redirects to the created peak" do
        post :create, :peak => valid_attributes
        response.should redirect_to(peaks_url)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved peak as @peak" do
        # Trigger the behavior that occurs when invalid params are submitted
        Peak.any_instance.stub(:save).and_return(false)
        post :create, :peak => {}
        assigns(:peak).should be_a_new(Peak)
      end

      it "re-renders the 'new' template" do
        pending "VALIDATION NOT IMPLEMENTED"
        # Trigger the behavior that occurs when invalid params are submitted
        Peak.any_instance.stub(:save).and_return(false)
        post :create, :peak => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested peak" do
        peak = Peak.create! valid_attributes
        # Assuming there are no other peaks in the database, this
        # specifies that the Peak created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Peak.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => peak.id, :peak => {'these' => 'params'}
      end

      it "assigns the requested peak as @peak" do
        peak = Peak.create! valid_attributes
        put :update, :id => peak.id, :peak => valid_attributes
        assigns(:peak).should eq(peak)
      end

      it "redirects to the peak" do
        peak = Peak.create! valid_attributes
        put :update, :id => peak.id, :peak => valid_attributes
        response.should redirect_to(peaks_url)
      end
    end

    describe "with invalid params" do
      it "assigns the peak as @peak" do
        peak = Peak.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Peak.any_instance.stub(:save).and_return(false)
        put :update, :id => peak.id.to_s, :peak => {}
        assigns(:peak).should eq(peak)
      end

      it "re-renders the 'edit' template" do
        pending "VALIDATION NOT IMPLEMENTED"
        peak = Peak.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Peak.any_instance.stub(:save).and_return(false)
        put :update, :id => peak.id.to_s, :peak => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested peak" do
      peak = Peak.create! valid_attributes
      expect {
        delete :destroy, :id => peak.id.to_s
      }.to change(Peak, :count).by(-1)
    end

    it "redirects to the peaks list" do
      peak = Peak.create! valid_attributes
      delete :destroy, :id => peak.id.to_s
      response.should redirect_to(peaks_url)
    end
  end

end
